stages:
  create_cfg:
      cmd: python create_yaml_cfg.py
      outs:
      - ./data/data_model.yaml
  val_model:
    cmd: python val_model.py
    deps:
    - ./data/data_model.yaml
    metrics:
    - metrics.json:
        cache: false