name: FV_Model Validation
on: 
  push:
    branches-ignore:
     -master
jobs:
  val-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Setup CML
        uses: iterative/setup-cml@v2
      
      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Install dependencies
        run: |
          echo "Installing DVC dependencies..."
          sudo apt update
          sudo apt install libssl-dev
          sudo apt install openssl
          sudo apt install unzip

          echo "Installing python packages..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pulling data from DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "Pulling data..."
          dvc pull
          
          echo "Unzip data..."
          unzip data/fruits_and_vegetables.zip -d data/
          unzip data/models.zip -d data/

      - name: Validate model
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Running DVC pipeline..."
          dvc repro -f

      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Fetching latest changes..."
          git fetch --prune

          echo "Generating metrics diff..."
          dvc metrics diff --md master > report.md

          echo "## Validating results" >> report.md
          echo '![](./val_output/val_metrics/confusion_matrix_normalized.png)' >> report.md

          echo "Sending report as a comment..."
          cml comment create report.md