name: FV_Model Validation
on: [push]
jobs:
  val-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Setup CML
        uses: iterative/setup-cml@v2
      
      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Install dependencies
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "Installing DVC dependencies..."
          sudo apt-get update
          sudo apt-get install libssl-dev
          sudo apt-get install --upgrade openssl
          python -m pip install --upgrade pip
          pip install --upgrade cryptography
          pip install --upgrade pyopenssl
          pip install dvc[gdrive]

          echo "Pulling data..."
          dvc pull

      - name: Validate model
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "Install requirements"
          pip install -r requirements.txt

          echo "Running DVC pipeline..."
          dvc repro

          echo "Fetching latest changes..."
          git fetch --prune

          echo "Generating metrics diff..."
          dvc metrics diff --md master > report.md

          echo "## Validating results" >> report.md
          cml-publish runs/detect/val/confusion_matrix_normalized.png --md >> report.md

          echo "Sending report as a comment..."
          cml-send-comment report.md