name: FV_Model Validation
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          # dvc remote modify myremote --local gdrive_service_account_json_file_path ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add figure to the report
          echo "## Validating results"
          cml-publish runs/detect/val/confusion_matrix_normalized.png --md >> report.md
          cml-send-comment report.md