name: Update weights in API repo

on:
  push:
    branches:
      - master
    paths:
      - data/models.zip.dvc

jobs:
  Auto-Update-Api-Weights:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone API repository
      env:
         PAT: ${{ secrets.PAT }}
      run: |
        cd ..
        git clone https://github.com/zamax14/Fruits_Vegetables_Detection_API.git

    - name: Pull weights from both repos
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        cd Fruits_Vegetables_Detection
        dvc pull
        unzip data/models.zip -d data/
        cd..

        cd Fruits_Vegetables_Detection_API
        dvc pull
        cd..

    - name: Copy weigths 
      run: |
        cp Fruits_Vegetables_Detection/data/models/best_v9.onnx Fruits_Vegetables_Detection_API/app/weigths/best_v9_9.onnx

    - name: Update DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        cd Fruits_Vegetables_Detection_API/
        dvc add ./app/weigths/best_v9_9.onnx
        #dvc push

    - name: Commit and push changes
      env:
          PAT: ${{ secrets.PAT }}
      run: |
        git add ./app/weigths/best_v9_9.onnx.dvc
        git commit -m "Update weights from Github Actions."
        #git push https://zamax14:${{ secrets.PAT }}@github.com/zamax14/Fruits_Vegetables_Detection_API.git
      
