name: Update weights in API repo

on:
  push:
    paths:
      - data/models.dvc

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone destination repository
      run: |
        git clone https://github.com/zamax14/Fruits_Vegetables_Detection_API.git
      env:
        PAT: ${{ secrets.PAT }}

    - name: Pull weights from both repos
      run: |
        cd /home/runner/work/Fruits_Vegetables_Detection/Fruits_Vegetables_Detection
        dvc pull
        cd /home/runner/work/Fruits_Vegetables_Detection/Fruits_Vegetables_Detection_API
        dvc pull

    - name: Copy weigths 
      run: |
        cp /home/runner/work/Fruits_Vegetables_Detection/Fruits_Vegetables_Detection/data/models/best_v9.onnx /home/runner/work/Fruits_Vegetables_Detection/Fruits_Vegetables_Detection_API/app/weigths/best_v9_9.onnx

    - name: Update DVC
      run: |
        cd /home/runner/work/Fruits_Vegetables_Detection/Fruits_Vegetables_Detection_API/
        dvc add ./app/weigths/best_v9_9.onnx
        dvc push

    - name: Commit and push changes
      run: |
        cd /home/runner/work/Fruits_Vegetables_Detection/Fruits_Vegetables_Detection_API/
        git add . 
        git commit -m "Update weights from Github Actions."
        git push https://zamax14:${{ secrets.PAT }}@github.com/zamax14/Fruits_Vegetables_Detection_API.git
      env:
        PAT: ${{ secrets.PAT }}