name: Update weights in API repo

on:
  push:
    branches:
      - master
    # paths:
    #   - data/models.zip.dvc

jobs:
  Auto-Update-Api-Weights:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        echo "Installing DVC dependencies..."
        sudo apt-get update
        sudo apt-get install libssl-dev
        sudo apt-get install --upgrade openssl
        sudo apt-get install unzip

        echo "Installing python packages..."
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt

    - name: Clone repository
      working-directory: ..
      env:
         PAT: ${{ secrets.PAT }}
      run: |
        git clone https://github.com/zamax14/Fruits_Vegetables_Detection_API.git
        echo "Clone completed"

    - name: Pull weights from model repo
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc pull
        unzip data/models.zip -d data/
        echo "Weights pulled"

    - name: Pull weights from api repo
      working-directory: ../Fruits_Vegetables_Detection_API
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc pull
        echo "Weights pulled"

    - name: Copy weigths 
      working-directory: ..
      run: |
        cp Fruits_Vegetables_Detection/data/models/best_v9.onnx Fruits_Vegetables_Detection_API/app/weigths/best_v9_9.onnx
        echo "Weights updated"

    - name: Update DVC
      working-directory: ../Fruits_Vegetables_Detection_API
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        cd Fruits_Vegetables_Detection_API/
        dvc add ./app/weigths/best_v9_9.onnx
        dvc push
        echo "Weights pushed to dvc"

    - name: Commit and push changes
      working-directory: ../Fruits_Vegetables_Detection_API
      env:
          PAT: ${{ secrets.PAT }}
      run: |
        git add ./app/weigths/best_v9_9.onnx.dvc
        git commit -m "Update weights from Github Actions."
        git push https://zamax14:${{ secrets.PAT }}@github.com/zamax14/Fruits_Vegetables_Detection_API.git
        echo "Changes in api repo pushed"
      
